name: Beautify Repository

on:
  push:
    branches:
      - main

jobs:
  beautify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
        
    - name: Set up Git
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your-email@example.com'
      
    - name: Beautify and Commit
      run: |
        NUMBER_OF_COMMITS=$((RANDOM % 5 + 1))
        echo "Committing $NUMBER_OF_COMMITS times."
        for ((i=1; i<=$NUMBER_OF_COMMITS; i++)); do
          echo "Commit #$i"
          echo "Random change $i" >> random_changes.txt
          git add .
          git commit -m "Random change $i"
        done
        git push

    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        pr_title: "Beautify: Random Changes"
        pr_body: "This pull request includes random changes."
        pr_branch: "beautify-branch-${{ github.run_number }}"
