name: Beautify Github Profile

on: 
  workflow_dispatch:

jobs:
  generate-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set Git user
      run: |
        git config user.email "dejanteofilovic2@gmail.com"
        git config user.name "Dejan-Teofilovic"

    - name: Make random number of commits (1-5)
      run: |
        for i in $(seq 1 $((1 + $RANDOM % 5))); do
          echo "$i" > random.txt
          git add random.txt
          git commit -m "Random commit $i"
        done

    - name: Push commits to main branch
      run: git push origin main

    - name: Create branch with random name and push
      run: |
        BRANCH_NAME=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 10 | head -n 1)
        git checkout -b $BRANCH_NAME
        git push origin $BRANCH_NAME

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5.0.2
      with:
        title: "Automated PR: Merging ${{ github.ref }} to main"
        branch: ${{ github.ref }}
        base: main
        delete-branch: true

    - name: Merge the pull request
      run: |
        PR_NUMBER=$(gh pr list --base main --json number --jq '.[0].number')
        gh pr merge $PR_NUMBER --auto --merge

      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
