name: Random Commits

on:
  workflow_dispatch:

jobs:
  random_commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate random commits
      run: |
        # Generating a random number between 1 to 5
        RANDOM_NUMBER=$(shuf -i 1-5 -n 1)
        echo "Generating $RANDOM_NUMBER commits."

        for i in $(seq 1 $RANDOM_NUMBER); do
          # Creating a random file name
          FILE_NAME=$(uuidgen)
          touch "$FILE_NAME.txt"
          echo "This is commit number $i on $(date)" > "$FILE_NAME.txt"

          git config --local user.email "dejanteofilovic2@gmail.com"
          git config --local user.name "Dejan-Teofilovic"
          git add "$FILE_NAME.txt"
          git commit -m "Adding random commit $i"
        done

        git push
