name: Beautify GitHub Profile

on: 
  workflow_dispatch:

jobs:
  beautify:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Make random number of commits (1-5)
      run: |
        for i in $(seq 1 $((1 + $RANDOM % 5))); do
          echo "$i" > random.txt
          git add random.txt
          git commit -m "Random commit $i"
        done

    - name: Push commits to main branch
      run: |
        git config user.email "dejanteofilovic2@gmail.com"
        git config user.name "Dejan-Teofilovic"
        git push

    - name: Create a new branch
      run: |
        branch_name=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
        git checkout -b $branch_name

    - name: Push new branch
      run: git push -u origin HEAD

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@5.0.2
      with:
        title: "Random PR"
        body: "This is an automated PR!"
        branch: ${{ steps.create_branch.outputs.branch_name }}
        base: main

    - name: Merge the PR
      run: |
        PR_number=$(gh pr list | grep "Random PR" | awk '{print $1}')
        gh pr merge $PR_number --merge

      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_COMMITTER_EMAIL: dejanteofilovic2@gmail.com
        GIT_AUTHOR_EMAIL: dejanteofilovic2@gmail.com
