name: Beautify GitHub Profile

on:
  workflow_dispatch:

jobs:
  beautify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Configure Git User
      run: |
        git config user.name "Dejan-Teofilovic"
        git config user.email "dejanteofilovic2@gmail.com"

    - name: Create Random Number of Commits (1-5)
      run: |
        for i in $(seq 1 $((1 + $RANDOM % 5))); do
          echo "Random data: $(date +%s) $RANDOM" >> random.txt
          git add random.txt
          git commit -m "Update random.txt"
        done

    - name: Fetch latest changes from main branch
      run: git fetch origin main

    - name: Merge the latest changes from main branch
      run: git merge origin/main

    - name: Push commits to main branch
      run: git push origin main

    - name: Create a new branch with a random string name
      run: |
        BRANCH_NAME=$(cat /proc/sys/kernel/random/uuid)
        git checkout -b $BRANCH_NAME

    - name: Push new branch to GitHub
      run: git push origin $BRANCH_NAME

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5.0.2
      with:
        title: 'Automated PR: Random Commits'
        commit-message: 'Add random commits'
        branch: ${{ steps.vars.outputs.branch }}
        base: main
        delete-branch: true

    - name: Merge Pull Request
      uses: gh pr merge ${{ steps.pr.outputs.pr_number }} --merge
